version: 2.1

jobs:
  deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install sudo
          command: apt-get update && apt-get install -y sudo

      - run:
          name: Install AWS CLI
          command: |
            apt-get update && apt-get install -y awscli
      - run:
          name: Configure AWS region
          command: |
            echo "export AWS_DEFAULT_REGION=us-east-1" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Configure AWS region
          command: |
            echo "export AWS_DEFAULT_REGION=us-east-1" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Configure AWS region
          command: |
            echo "export AWS_DEFAULT_REGION=us-east-1" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Configure AWS region
          command: |
            echo "export AWS_DEFAULT_REGION=us-east-1" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Configure AWS region
          command: |
            aws configure set default.region us-east-1
      - run:
          name: Configure AWS credentials
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - run:
          name: Terraform init
          command: terraform init
      - run:
          name: Terraform validate
          command: terraform validate
      - run:
          name: Terraform plan
          command: terraform plan
      - run:
          name: Terraform apply
          command: terraform apply -auto-approve

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
      - deploy:
          filters:
            branches:
              only: /^pull\/.*$/